### ISSUE TITLE
Username/Password exposed in input file

### ISSUE THREAD

**Issue by vsnyc** [StutiAngra/aws-quickstart-informatica-tableau#11]
https://github.com/StutiAngra/aws-quickstart-informatica-tableau/blob/c4bdeac797a0e711a16298002bc4782391652132/ci/tableau-informatica-awsdata-master.json#L94-L101

Unless invalid, you may want to remove these as the file is public. Also, the email is exposed and could be a privacy concern.

**Comment by StutiAngra** [comment]
I have removed my parameter file from the location . Thank you.
