### ISSUE TITLE
Use template from Tableau Quick Start

### ISSUE THREAD

**Issue by vsnyc** [StutiAngra/aws-quickstart-informatica-tableau#12]
https://github.com/StutiAngra/aws-quickstart-informatica-tableau/blob/c4bdeac797a0e711a16298002bc4782391652132/templates/tableau-awsdata.template#L652

Is this a copy of the template in Tableau Quick Start? If not, what was modified?

**Comment by StutiAngra** [comment]
It is not the copy of the template .
Changes in the templates : 
1. The AMI's have changed ( Changes in AMI : Tableau Version , Python Version , Tableau Server Manager is added )
2. Datasources are used from the bucket cfn-register.
3. First tableau was using postgres as a database , now this has changed to Oracle RDS.
