### ISSUE TITLE
Need for RemoteAccessCIDR and InboundTraffic

### ISSUE THREAD

**Issue by vsnyc** [StutiAngra/aws-quickstart-informatica-tableau#2]
https://github.com/StutiAngra/aws-quickstart-informatica-tableau/blob/c4bdeac797a0e711a16298002bc4782391652132/templates/redshift-cluster.template#L42-L50

What is the need for two separate parameters. The RedShift cluster is placed in private subnet so won't be accessible from the RemoteAccessCIDR

**Comment by StutiAngra** [comment]
RemoteAccessCIDR will be used to make Redshift accessible in the CIDR range provided by user . 
InboundTraffic will be used to make Redshift available in the particular VPC ( so we are passing VPC CIDR ),

**Comment by StutiAngra** [comment]
Removing RemoteAccessCIDR from the Redshift cluster template as Redshift is in private subnet.
