### ISSUE TITLE
LambdaStack, LambdaMappingStack, LambdaLicenseStack invoked twice

### ISSUE THREAD

**Issue by vsnyc** [StutiAngra/aws-quickstart-informatica-tableau#3]
https://github.com/StutiAngra/aws-quickstart-informatica-tableau/blob/c4bdeac797a0e711a16298002bc4782391652132/templates/tableau-awsdata-master.template#L484-L538

LambdaStack, LambdaMappingStack, LambdaLicenseStack are being invoked twice when tableau-awsdata-master.template is launched, once from the master template and once from tableau-awsdata.template

**Comment by StutiAngra** [comment]
After launching a stack in existing VPC or in new  VPC , we need to check If the resources are already present in the users account .

**Comment by StutiAngra** [comment]
Iam removing the stacks from the master template , the check will be done after launching VPC and RDGW stack.

**Comment by vsnyc** [comment]
Works for now. Lambda check may be desirable in the master stack to fail fast but then it shouldn't be repeated in the nested stack.
