### ISSUE TITLE
cfn-register bucket

### ISSUE THREAD

**Issue by vsnyc** [StutiAngra/aws-quickstart-informatica-tableau#5]
https://github.com/StutiAngra/aws-quickstart-informatica-tableau/blob/c4bdeac797a0e711a16298002bc4782391652132/templates/tableau-awsdata.template#L755

Which bucket is this: `cfn-register` and why is it hard-coded? The iam template takes `InformaticaLicenseBucket` as an input parameter but won't be able to take external input

**Comment by StutiAngra** [comment]
We are using a 2 month valid license file for Informatica EDC from the following bucket . 
I can remove this from IAM template.

**Comment by vsnyc** [comment]
Mapping is okay but I recommend using a different bucket name e.g. informatica-quickstart

**Comment by vsnyc** [comment]
Similar suggestions provided in Issue #8. Resolving this as duplicate
