### ISSUE TITLE
CidrIp Query

### ISSUE THREAD

**Issue by vsnyc** [StutiAngra/aws-quickstart-informatica-tableau#6]
https://github.com/StutiAngra/aws-quickstart-informatica-tableau/blob/c4bdeac797a0e711a16298002bc4782391652132/templates/informatica-security-group.template#L82-L503

Are these CidrIp ranges owned by Informatica?

**Comment by StutiAngra** [comment]
Yes , the above IP's are owned by Informatica .We are using the above security group rule to avoid any connection issues with  Informatica Intelligent Cloud Services .

**Comment by vsnyc** [comment]
Sounds good.
